CREATE TABLE api_clients (
	id CHAR(36) PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	api_key_hash VARCHAR(255) NOT NULL,
	allowed_fields JSON NOT NULL,
	rate_limit_max INT NOT NULL DEFAULT 60,
	rate_limit_window_seconds INT NOT NULL DEFAULT 60,
	enabled BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
