FROM node:22-nanoserver-ltsc2022 AS web
WORKDIR C:\\web
COPY web/package.json web/package-lock.json .
RUN npm ci
COPY web/ .
RUN npm run build

FROM golang:1.26-nanoserver-ltsc2022 AS build
WORKDIR C:\\src
COPY go.mod go.sum .
RUN go mod download
COPY . .
COPY --from=web C:\\web\\out\\ internal\\webui\\dist\\
RUN go build -ldflags "-s -w" -o C:\\out\\idpforge-server.exe .\\cmd\\server

FROM mcr.microsoft.com/windows/nanoserver:ltsc2022
COPY --from=build C:\\out\\idpforge-server.exe C:\\idpforge\\idpforge-server.exe
EXPOSE 8080
ENTRYPOINT ["C:\\idpforge\\idpforge-server.exe"]
